import { jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import "@mysten/dapp-kit/dist/index.css";
import "@radix-ui/themes/styles.css";
import { SuiClientProvider, WalletProvider } from "@mysten/dapp-kit";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Theme } from "@radix-ui/themes";
import App from "./App.tsx";
import { networkConfig } from "./networkConfig.ts";
const queryClient = new QueryClient();
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(Theme, { appearance: "dark", children: _jsx(QueryClientProvider, { client: queryClient, children: _jsx(SuiClientProvider, { networks: networkConfig, defaultNetwork: "testnet", children: _jsx(WalletProvider, { autoConnect: true, children: _jsx(App, {}) }) }) }) }) }));
